### ISSUE TITLE
Artifact upload - intermittent internal server error

### ISSUE THREAD

**Issue by devlead** [appveyor/ci#1006]
Noticed daily intermittent internal server errors when uploading artifacts to AppVeyor using appveyor.exe, it's not the same files that fail, but the file will fail with in same build if we do a retry.

Basically what we see in the console log is
`Error pushing artifact: The remote server returned an error: (500) Internal Server Error.`

A few recent example builds
* This one missing full & core clr zip
https://ci.appveyor.com/project/cakebuild/cake/build/0.16.0-PullRequest.1201+77.build.2714
[![image](https://cloud.githubusercontent.com/assets/1647294/18094603/63015ef8-6ed4-11e6-90ca-8b6095028d5c.png)](https://ci.appveyor.com/project/cakebuild/cake/build/0.16.0-PullRequest.1201+77.build.2714/artifacts)

* This one is missing the test results zip.
https://ci.appveyor.com/project/cakebuild/cake/build/0.16.0-PullRequest.1201+77.build.2713
[![image](https://cloud.githubusercontent.com/assets/1647294/18094109/a3b16882-6ed2-11e6-9fd2-5f23c2a8273b.png)](https://ci.appveyor.com/project/cakebuild/cake/build/0.16.0-PullRequest.1201+77.build.2713/artifacts)

* This one is missing test results & core clr zip
https://ci.appveyor.com/project/cakebuild/cake/build/0.16.0-PullRequest.1201+76.build.2707#L1963
[![image](https://cloud.githubusercontent.com/assets/1647294/18094020/56fd4aec-6ed2-11e6-91a6-4f5af21fc94f.png)](https://ci.appveyor.com/project/cakebuild/cake/build/0.16.0-PullRequest.1201+76.build.2707/artifacts)

* this one is missing the core clr zip
https://ci.appveyor.com/project/cakebuild/cake/build/0.16.0-PullRequest.1201+77.build.2711
[![image](https://cloud.githubusercontent.com/assets/1647294/18094365/888f0d6a-6ed3-11e6-8bdf-de5cffdaa642.png)](https://ci.appveyor.com/project/cakebuild/cake/build/0.16.0-PullRequest.1201+77.build.2711/artifacts)

**Comment by FeodorFitsner** [comment]
We're working on the solution at the moment. Will deploy a fix later this week.

**Comment by devlead** [comment]
Great 👍

**Comment by FeodorFitsner** [comment]
Another case: http://help.appveyor.com/discussions/problems/1041-push-appveyorartifact-failing-with-500-error

**Comment by FeodorFitsner** [comment]
We've deployed an updated image where artifacts upload process was drastically improved! Let me know how that worked.

**Comment by devlead** [comment]
@FeodorFitsner excellent👍 will run a few builds to see if it's resolved for us. Is this related to #997 or it's that a separate issue?

**Comment by FeodorFitsner** [comment]
We've rolled back images for now: https://www.appveyor.com/updates/2016/09/09/, sorry. When they are fixed you can do your tests again.

**Comment by devlead** [comment]
Ok then I'll hold off :wink: , when fixed will it address tests issues too (#997)?

**Comment by FeodorFitsner** [comment]
Give it a try again - the image with update is back.

**Comment by devlead** [comment]
Ok will do!

**Comment by devlead** [comment]
Will have to test again but first try yielded errors
![image](https://cloud.githubusercontent.com/assets/1647294/18643495/ab4a4fb8-7ea5-11e6-9ac8-faae03a7492f.png)
https://ci.appveyor.com/project/cakebuild/cake/build/0.17.0-alpha.6.build.2799#L1397

**Comment by FeodorFitsner** [comment]
What command do you use to upload artifacts?

**Comment by devlead** [comment]
appveyor exe with `PushArtifact` and `-Type` set to `Auto`

**Comment by devlead** [comment]
Tried rebuilding a PR that worked 10hrs ago, same issue.
https://ci.appveyor.com/project/cakebuild/cake/build/0.17.0-PullRequest.1141+7.build.2800#L1373

**Comment by devlead** [comment]
Maybe unrelated but a SQL assembly that's build same commit successfully for 2 months started to yield build errors
https://ci.appveyor.com/project/WCOMAB/sqlserverslackapi/history

**Comment by FeodorFitsner** [comment]
We've rolled out update this morning: https://www.appveyor.com/updates/2016/09/19/

**Comment by FeodorFitsner** [comment]
Can you please add the following to your appveyor.yml to see what's going on with upload:

    on_failure:
    - ps: Get-EventLog AppVeyor -newest 10 | Format-List

**Comment by FeodorFitsner** [comment]
Can you point me to a place in build script where actual upload is occurred/called?

**Comment by devlead** [comment]
Artifacts are uploaded here:
https://github.com/cake-build/cake/blob/develop/build.cake#L309

I'll try to make a PR to test Get-EventLog later.

**Comment by FeodorFitsner** [comment]
OK, rolled back images for now. Will be investigating.

**Comment by FeodorFitsner** [comment]
Regarding this issue: https://ci.appveyor.com/project/WCOMAB/sqlserverslackapi/build/1.0.391 - what would be the simplest repro?

**Comment by devlead** [comment]
Ok just submitted an pr with get-eventlog on finnish :wink:

Regarding sql, well it's on GitHub, but if you rolled back I'll just rebuild and see if it compiles now. If not it could be something unrelated.

**Comment by FeodorFitsner** [comment]
Yeah, but I was hoping you can help me with possibly a simple repro, without me digging into all details of the project/codebase?

**Comment by devlead** [comment]
Of course, I'll just see if it builds now :) 

Btw. this is the PR with eventlog perhaps tune it to last include more events?

**Comment by devlead** [comment]
It now builds same commit without issue
https://ci.appveyor.com/project/WCOMAB/sqlserverslackapi/build/1.0.393

**Comment by FeodorFitsner** [comment]
Yeah, we've found the issue with artifact upload - will be fixed today. Help me understand that sql issue on a different project?

**Comment by devlead** [comment]
See that you updated to SQL Server Data Tools 16.3, could be that the project has an issue with that. I'll just see if I can reproduce error locally.

**Comment by devlead** [comment]
Just FYI the project is
https://github.com/WCOMAB/SqlServerSlackAPI

Think I'm running latest bits locally so I'll just see if it compiles without issue locally first.

**Comment by FeodorFitsner** [comment]
I'm doing some tests now: https://ci.appveyor.com/project/appveyor-tests/artifacts-upload-in-cake/build/0.17.0-alpha.6.build.1#L1458

What are those `The remote server returned an error: (500) Internal Server Error.`?

**Comment by devlead** [comment]
I suspect those are from the 3 artifacts that didn't get uploaded should be 13.

**Comment by FeodorFitsner** [comment]
What are those artifacts? What's the difference between upload those 3 and the rest of artifacts?

**Comment by FeodorFitsner** [comment]
Can you drop me a link to a line where those 3 artifacts uploading?

**Comment by devlead** [comment]
Well this build has all 13 artifacts
https://ci.appveyor.com/project/cakebuild/cake/build/0.17.0-PullRequest.1141+7.build.2797/artifacts

This build has 10 artifacts
https://ci.appveyor.com/project/cakebuild/cake/build/0.16.1-PullRequest.1238+5.build.2794/artifacts

This build has 10 artifacts
https://ci.appveyor.com/project/cakebuild/cake/build/0.17.0-PullRequest.1143+26.build.2796/artifacts

This build has all 13 artifacts
https://ci.appveyor.com/project/cakebuild/cake/build/0.17.0-alpha.4.build.2792/artifacts

Build script hasn't changed between these builds, artifacts are uploaded [here](https://github.com/cake-build/cake/blob/develop/build.cake#L309-L314)

It's all done in a tight loop, same command utilizing the AppVeyor command line with args `PushArtifact -Type Auto`

**Comment by devlead** [comment]
Now added 30 event log entries to pr log

This build results in 11 artifacts
https://ci.appveyor.com/project/cakebuild/cake/build/0.17.0-PullRequest.1239+10.build.2804

This build results in 10 artifacts
https://ci.appveyor.com/project/cakebuild/cake/build/0.17.0-PullRequest.1239+10.build.2803

Different files having issues each time.

The evenlog errors might be what your looking for
```
[00:04:13] Index              : 671
[00:04:13] EntryType          : Warning
[00:04:13] InstanceId         : 0
[00:04:13] Message            : Build Worker API error (POST http://localhost:1031/api/artifacts): System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
[00:04:13]                         at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
[00:04:13]                         at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
[00:04:13]                         at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
[00:04:13]                         at Appveyor.BuildAgent.BuildContext.AddOrUpdateArtifact(BuildArtifactModel artifact)
[00:04:13]                         at Appveyor.BuildAgent.Controllers.ArtifactsController.<PushArtifact>d__4.MoveNext()
[00:04:13]                      --- End of stack trace from previous location where exception was thrown ---
[00:04:13]                         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[00:04:13]                         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[00:04:13]                         at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()
[00:04:13]                      --- End of stack trace from previous location where exception was thrown ---
[00:04:13]                         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[00:04:13]                         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[00:04:13]                         at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
[00:04:13]                      --- End of stack trace from previous location where exception was thrown ---
[00:04:13]                         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[00:04:13]                         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[00:04:13]                         at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
[00:04:13]                      --- End of stack trace from previous location where exception was thrown ---
[00:04:13]                         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[00:04:13]                         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[00:04:13]                         at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
[00:04:13] Category           : (0)
[00:04:13] CategoryNumber     : 0
[00:04:13] ReplacementStrings : {Build Worker API error (POST http://localhost:1031/api/artifacts): System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
[00:04:13]                         at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
[00:04:13]                         at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
[00:04:13]                         at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
[00:04:13]                         at Appveyor.BuildAgent.BuildContext.AddOrUpdateArtifact(BuildArtifactModel artifact)
[00:04:13]                         at Appveyor.BuildAgent.Controllers.ArtifactsController.<PushArtifact>d__4.MoveNext()
[00:04:13]                      --- End of stack trace from previous location where exception was thrown ---
[00:04:13]                         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[00:04:13]                         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[00:04:13]                         at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()
[00:04:13]                      --- End of stack trace from previous location where exception was thrown ---
[00:04:13]                         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[00:04:13]                         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[00:04:13]                         at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
[00:04:13]                      --- End of stack trace from previous location where exception was thrown ---
[00:04:13]                         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[00:04:13]                         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[00:04:13]                         at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
[00:04:13]                      --- End of stack trace from previous location where exception was thrown ---
[00:04:13]                         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[00:04:13]                         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[00:04:13]                         at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()}
```
Similar errors in both builds
https://ci.appveyor.com/project/cakebuild/cake/build/0.17.0-PullRequest.1239+10.build.2803#L1644
and
https://ci.appveyor.com/project/cakebuild/cake/build/0.17.0-PullRequest.1239+10.build.2804#L1532

**Comment by devlead** [comment]
Almost looks like someone is using i list as a concurrent queue.

**Comment by devlead** [comment]
_FYI rebuild same PR with extra logging a few times, so same code, same build script, but different files that fail._

| Build               | Artifact count |
|----------------|-----------------|
|[0.17.0-PullRequest.1239+10.build.2809](https://ci.appveyor.com/project/cakebuild/cake/build/0.17.0-PullRequest.1239+10.build.2809)| 11|
|[0.17.0-PullRequest.1239+10.build.2808](https://ci.appveyor.com/project/cakebuild/cake/build/0.17.0-PullRequest.1239+10.build.2808) | 11 |
|[0.17.0-PullRequest.1239+10.build.2807](https://ci.appveyor.com/project/cakebuild/cake/build/0.17.0-PullRequest.1239+10.build.2807) | 10 |
|[0.17.0-PullRequest.1239+10.build.2806](https://ci.appveyor.com/project/cakebuild/cake/build/0.17.0-PullRequest.1239+10.build.2806)| 8 |
|[0.17.0-PullRequest.1239+10.build.2805](https://ci.appveyor.com/project/cakebuild/cake/build/0.17.0-PullRequest.1239+10.build.2805) | 10 |
|[0.17.0-PullRequest.1239+10.build.2804](https://ci.appveyor.com/project/cakebuild/cake/build/0.17.0-PullRequest.1239+10.build.2804) | 11 |
|[0.17.0-PullRequest.1239+10.build.2803](https://ci.appveyor.com/project/cakebuild/cake/build/0.17.0-PullRequest.1239+10.build.2803) | 10 |

**Comment by FeodorFitsner** [comment]
Thanks, that helps!

**Comment by FeodorFitsner** [comment]
An updated image is on the way - should be available in a few hours. SSDT issue fixed as well.

**Comment by devlead** [comment]
ah superb 👍 thanks!

**Comment by FeodorFitsner** [comment]
OK, it's done - update image has been applied! Upload is reliable as never before 😄 Give it a try.
Btw, there is a new `-Verbosity` option in `appveyor PushArtifact` command which can make your logs nicer. Try using `-Verbosity Minimal`.

**Comment by devlead** [comment]
Splendid, I'll take it for a spin.

**Comment by devlead** [comment]
@FeodorFitsner have now executed 3 builds, which all successfully uploaded all artifacts 👍 
Cool with new options, what are the possible verbosities?

**Comment by FeodorFitsner** [comment]
Quiet, Minimal and Normal

**Comment by devlead** [comment]
Thanks 👍  it's there a complete in one place documentation of the AppVeyor executable available somewhere?

**Comment by FeodorFitsner** [comment]
It's here: https://www.appveyor.com/docs/build-worker-api/#push-artifact

**Comment by devlead** [comment]
Thanks 👍

**Comment by Grinderofl** [comment]
Hi, I seem to be experiencing a similar issue with uploading test results. The results coming back from the server are basically 500's. I'm using cake build as the script.

If you can access the private build: https://ci.appveyor.com/project/StormID/storm-domain/build/1.0.0-PullRequest-9be11fca+10047 

Here's a git from another build https://ci.appveyor.com/project/StormID/storm-domain/build/1.0.0-PullRequest-7528ac91+10045 which contains the diagnostic log with the full exception and stack trace, I've also created a gist with the exception and get-eventlog https://gist.github.com/Grinderofl/b1b0c5fd8d772a31a990eb5aa4cd7f31 

I'm not quite sure what's happening there, is it possible to obtain better logs?

**Comment by FeodorFitsner** [comment]
@Grinderofl Are you uploading XML test results, right? Is is possible to see the sources of `Cake.Common.Net.HttpClientExtensions.UploadTestResults` method?

**Comment by Grinderofl** [comment]
@FeodorFitsner Yes. I get varying degrees of success - sometimes I get 100% success, other times I get errors. I've decided to catch it for current purposes, because it's only about test results, but I can see it becoming a problem when we don't want to catch anything.

I don't know about UploadTestResults method, but here's the HttpClientExtensions file:

https://github.com/cake-build/cake/blob/develop/src/Cake.Common/Net/HttpClientExtensions.cs

**Comment by FeodorFitsner** [comment]
I see. It might be an issue with parsing XML results then. Can you send the XML to team@ please?

**Comment by devlead** [comment]
@Grinderofl @FeodorFitsner this is the UploadTestResults method
https://github.com/cake-build/cake/blob/develop/src/Cake.Common/Build/AppVeyor/AppVeyorProvider.cs#L222

Looks like if you launch Cake with diagnostic verbosity you'll get some more logging, that perhaps might be useful.

**Comment by Grinderofl** [comment]
The XML from one of the failed builds:

https://gist.github.com/Grinderofl/fd5a423e91d629885285c066f7893575

I can see that the jobID gets converted to lowercase in there upload method. Do you reckon that has any relevance to the upload?

**Comment by IlyaFinkelshteyn** [comment]
XML is perfectly fine XUnit test result. Given errors I found in our traces, the fact that it was intermittent and other problems we had last weeks, I believe this is our internal dependency (Redis cache) issue which should be fixed on weekend. Could you please try stop catching those errors and see if they come back?
