### ISSUE TITLE
AspNetCore 1.1 Test Started to fail

### ISSUE THREAD

**Issue by StummeJ** [appveyor/ci#1360]
We've just started receiving this runtime error when trying to run aspnet core 1.1 tests targeting net46 on the visual studio 2015 images:

```
System.TypeLoadException : Method 'get_ContentLength' in type Microsoft.AspNetCore.Http.HeaderDictionary' from assembly 'Microsoft.AspNetCore.Http, Version=1.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.
      Stack Trace:
           at Microsoft.AspNetCore.Http.Features.HttpRequestFeature..ctor()
           at Microsoft.AspNetCore.Http.DefaultHttpContext..ctor()
```

We've rebuilt a previous green job and it has started to fail in this same manor.

**Comment by FeodorFitsner** [comment]
There were no recent changes to build worker images: https://www.appveyor.com/updates/
Could it be an external dependency that changed? Exception says method implementation changed.

**Comment by StummeJ** [comment]
This would be odd as a previous build also started to fail.  Converting the project over to .net core and packaging the runtime with the project provided a green build though.

**Comment by FeodorFitsner** [comment]
I guess `Microsoft.AspNetCore.Http` is pulling as a nuget package during the build. Maybe something changed on that feed.

Can you do a simple repro app in a public repository?

**Comment by deepblue08** [comment]
> This would be odd as a previous build also started to fail. Converting the project over to .net core and packaging the runtime with the project provided a green build though.

Installing Microsoft.AspNetCore.Http via NuGet fixed this error for me.
