### ISSUE TITLE
SQL Server 2017 support in "SqlDatabase" deployment provider

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#1552]

**Comment by mloskot** [comment]
Does this mean to add SQL Server 2017 to the services?

**Comment by FeodorFitsner** [comment]
Not yet, it's for SqlDatabase deployment provider to be able to deploy to SQL Server 2017 (Azure SQL specifically).

When SQL Server 2017 is RTM'ed we'll deploy to it to build worker images.

**Comment by mloskot** [comment]
Gotcha, thanks

**Comment by PhilOchu** [comment]
Good day @FeodorFitsner. Do you know if the AppVeyor Deployment Agent will deploy dacpacs to SQL Server 2017 - I believe it is RTM now.

I have an issue with AppVeyor agent (5.0.8.218) returning the following error:

```
Microsoft.SqlServer.Dac.DacServicesException: Could not deploy package. ---> Microsoft.Data.Tools.Schema.Sql.Deployment.DeploymentFailedException: Unable to connect to master or target server '{DATABASENAME}'. You must have a user with the same password in master or target server '{DATABASENAME}'.
   at Microsoft.Data.Tools.Schema.Sql.Deployment.SqlDeploymentEndpointServer.OnInit(ErrorManager errors, String targetDBName)
   at Microsoft.Data.Tools.Schema.Sql.Deployment.SqlDeployment..ctor(SqlDeploymentConstructor constructor)
   at Microsoft.Data.Tools.Schema.Sql.Deployment.SqlDeploymentConstructor.ConstructServiceImplementation()
   at Microsoft.SqlServer.Dac.DacServices.CreatePackageToDatabaseDeployment(SqlConnectionFactory connectionFactory, IPackageSource packageSource, String targetDatabaseName, DacDeployOptions options, ErrorManager errorManager)
   at Microsoft.SqlServer.Dac.DeployOperation.<>c__DisplayClass3.<>c__DisplayClass5.<CreatePlanInitializationOperation>b__1()
```
This is running on an Amazon EC2 instance (if that helps). It seems to work fine against older SQL Server databases.

I am also able to manually deploy dacpac using sqlpackage.exe on the VM - so I think (but not sure) it might be a code/dll reference issue.

What do you think?

**Comment by FeodorFitsner** [comment]
Related discussion: https://help.appveyor.com/discussions/problems/10509-unable-to-deploy-to-sql-server-2017-database-using-appveyor-agent-508

**Comment by FeodorFitsner** [comment]
The publishing to SQL Server 2017 is possible now!
