### ISSUE TITLE
NUnit.ConsoleRunner 3.6.1 causing failing builds due to AppDomain exception

### ISSUE THREAD

**Issue by mjbettinson** [appveyor/ci#1812]
Hi!

We have attempted to upgrade some test projects from NUnit 2.6.4 to NUnit 3.8.1 - however, we have observed a consistent build failure due to an exception being thrown from NUnit at the end of the test run (despite all tests passing).

The following is an excerpt of the build log.

Unhandled Exception: NUnit.Engine.NUnitEngineException: Exception encountered unloading AppDomain
Agent Process was terminated successfully after error.
   at NUnit.Engine.Runners.ProcessRunner.Dispose(Boolean disposing)
   at NUnit.Engine.Runners.AbstractTestRunner.Dispose()
   at NUnit.Engine.Runners.TestExecutionTask.Execute()
   at NUnit.Engine.Runners.ParallelTaskWorkerPool.ProcessTasksProc()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

We observed that the NUnit.ConsoleRunner used for NUnit 3.X projects is 3.6.1 (NUnit 2.X projects were observed to be using 2.6.4).

After a quick google, we also found there is an outstanding issue with NUnit themselves around 3.6.1 with this exact exception - https://github.com/nunit/nunit-console/issues/191

With this information in mind, we were wondering about a couple of options.

Is it possible for us to force the AppVeyor build server to target NUnit.ConsoleRunner 3.5 (apparently a version where this wasn't an issue) for a specific project whilst this is apparently a problem for 3.6.1?  There is a new 3.7.0 version - however, as the issue is still open it would appear it has not been addressed yet.

**Comment by IlyaFinkelshteyn** [comment]
Hi!
You can  add the following PowerShell script (or commands directly in YAML) at `install` stage:

```
Write-Host "Installing NUnit 3.5.0..." -ForegroundColor Cyan -NoNewline
$toolsPath = "$env:SYSTEMDRIVE\Tools"
$nunitPath = "$env:SYSTEMDRIVE\Tools\NUnit3"

Remove-Item $nunitPath -Recurse -Force -erroraction ignore

# nunit
$zipPath = "$($env:TEMP)\NUnit.Console-3.5.0.zip"
(New-Object Net.WebClient).DownloadFile('https://github.com/nunit/nunit-console/releases/download/3.5/NUnit.Console-3.5.0.zip', $zipPath)
7z x $zipPath -y -o"$nunitPath" | Out-Null
del $zipPath

# logger
$zipPath = "$($env:TEMP)\Appveyor.NUnit3Logger.zip"
(New-Object Net.WebClient).DownloadFile('http://www.appveyor.com/downloads/Appveyor.NUnit3Logger.zip', $zipPath)
7z x $zipPath -y -o"$nunitPath\addins" | Out-Null
Move-Item "$nunitPath\addins\appveyor.addins" "$nunitPath\appveyor.addins"
del $zipPath

Remove-Path "$nunitPath\bin"
Add-Path "$nunitPath"

Write-Host "NUnit 3.5.0 installed" -ForegroundColor Green
```

**Comment by mjbettinson** [comment]
Thanks for your prompt reply!

I have tried the recommended Powershell and it did indeed force the install and use of NUnit.ConsoleRunner 3.5.0.

Unfortunately, there seems to be a couple of issues.

The AppVeyor.NUnit3Logger seems to be throwing an exception at all points it has attempted to do some logging from the tests.
The following is one such example (in the example, the log message is an information message stating that our test has closed an instance of RabbitMQ that was running for the purposes of the test):

Error in log handler
====================
Event: {info_msg,<0.94.0>,
                 {<0.669.0>,"closing AMQP connection ~p (~s)~n",
                  [<0.669.0>,"[::1]:1815 -> [::1]:5675"]}}
Error: function_clause
Stack trace: [{error_logger_file_h,write_event,
                  [{<0.68.0>,
                    "C:/Users/appveyor/AppData/Local/Temp/1/rabbitMQ_eysodlwv.mtw/log/rabbitfunctionaltests.log",
                    []},
                   {info_msg,<0.94.0>,
                       {<0.669.0>,"closing AMQP connection ~p (~s)~n",
                        [<0.669.0>,"[::1]:1815 -> [::1]:5675"]}}],
                  [{file,"error_logger_file_h.erl"},{line,114}]},
              {error_logger_file_h,handle_event,2,
                  [{file,"error_logger_file_h.erl"},{line,79}]},
              {rabbit_error_logger_file_h,safe_handle_event,3,[]},
              {gen_event,server_update,4,[{file,"gen_event.erl"},{line,533}]},
              {gen_event,server_notify,4,[{file,"gen_event.erl"},{line,515}]},
              {gen_event,server_notify,4,[{file,"gen_event.erl"},{line,517}]},
              {gen_event,handle_msg,5,[{file,"gen_event.erl"},{line,256}]},
              {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]

A second issue is that unfortunately we are still seeing the same exception against NUnit.ConsoleRunner 3.5.0 as originally reported for 3.6.1 (unless it's now something to do with the AppVeyor.NUnit3Logger exceptions reported above - unlikely but I'm unsure), so it would appear that this hasn't changed anything (contrary to what others had seemingly reported).

Do you have any recommendations about the logging issue?  I would very much like to verify the original exception without the introduction of this new one so we can definitely establish if 3.5.0 is viable.
Could this be a dependency issue? The NUnit.ConsoleRunner being 3.5.0, the tests themselves being 3.81, and then whatever version of NUnit 3 the AppVeyor.NUnit3Logger is referencing?

**Comment by IlyaFinkelshteyn** [comment]
@mjbettinson is there any way you could create a repro in a public repository for us to investigate?
