### ISSUE TITLE
Dealing with libcurl.dll on AppVeyor [question]

### ISSUE THREAD

**Issue by ashmaroli** [appveyor/ci#1959]
I'm having trouble running a build that requires access to `libcurl.dll` or `libcurl.so.4`.
I couldn't find a solution online nor in the docs for AppVeyor.
Any help would be appreciated. Thanks.

Reference Error Message:
```
sh ./script/cibuild
C:/projects/jekyll-remote-theme/vendor/bundle/ruby/2.2.0/gems/ffi-1.9.18-x86-mingw32/lib/ffi/library.rb:147:in `block in ffi_lib': Could not open library 'libcurl': ��(. (LoadError)
Could not open library 'libcurl.dll': ��(.
Could not open library 'libcurl.so.4': The specified module could not be found.

Could not open library 'libcurl.so.4.dll': The specified module could not be found.
  from C:/projects/jekyll-remote-theme/vendor/bundle/ruby/2.2.0/gems/ffi-1.9.18-x86-mingw32/lib/ffi/library.rb:100:in `map'
  from C:/projects/jekyll-remote-theme/vendor/bundle/ruby/2.2.0/gems/ffi-1.9.18-x86-mingw32/lib/ffi/library.rb:100:in `ffi_lib'
  from C:/projects/jekyll-remote-theme/vendor/bundle/ruby/2.2.0/gems/ethon-0.11.0/lib/ethon/curls/settings.rb:7:in `<module:Curl>'
  from C:/projects/jekyll-remote-theme/vendor/bundle/ruby/2.2.0/gems/ethon-0.11.0/lib/ethon/curls/settings.rb:2:in `<module:Ethon>'
  from C:/projects/jekyll-remote-theme/vendor/bundle/ruby/2.2.0/gems/ethon-0.11.0/lib/ethon/curls/settings.rb:1:in `<top (required)>'
  from C:/projects/jekyll-remote-theme/vendor/bundle/ruby/2.2.0/gems/ethon-0.11.0/lib/ethon/curl.rb:27:in `require'
  from C:/projects/jekyll-remote-theme/vendor/bundle/ruby/2.2.0/gems/ethon-0.11.0/lib/ethon/curl.rb:27:in `<module:Curl>'
  from C:/projects/jekyll-remote-theme/vendor/bundle/ruby/2.2.0/gems/ethon-0.11.0/lib/ethon/curl.rb:13:in `<module:Ethon>'
  from C:/projects/jekyll-remote-theme/vendor/bundle/ruby/2.2.0/gems/ethon-0.11.0/lib/ethon/curl.rb:8:in `<top (required)>'
  from C:/projects/jekyll-remote-theme/vendor/bundle/ruby/2.2.0/gems/ethon-0.11.0/lib/ethon.rb:15:in `require'
  from C:/projects/jekyll-remote-theme/vendor/bundle/ruby/2.2.0/gems/ethon-0.11.0/lib/ethon.rb:15:in `<top (required)>'
  from C:/projects/jekyll-remote-theme/vendor/bundle/ruby/2.2.0/gems/typhoeus-1.3.0/lib/typhoeus.rb:2:in `require'
  from C:/projects/jekyll-remote-theme/vendor/bundle/ruby/2.2.0/gems/typhoeus-1.3.0/lib/typhoeus.rb:2:in `<top (required)>'
  from C:/projects/jekyll-remote-theme/lib/jekyll-remote-theme.rb:7:in `require'
  from C:/projects/jekyll-remote-theme/lib/jekyll-remote-theme.rb:7:in `<top (required)>'
  from C:/projects/jekyll-remote-theme/spec/spec_helper.rb:3:in `require_relative'
  from C:/projects/jekyll-remote-theme/spec/spec_helper.rb:3:in `<top (required)>'
  from C:/projects/jekyll-remote-theme/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.7.0/lib/rspec/core/configuration.rb:1455:in `require'
  from C:/projects/jekyll-remote-theme/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.7.0/lib/rspec/core/configuration.rb:1455:in `block in requires='
  from C:/projects/jekyll-remote-theme/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.7.0/lib/rspec/core/configuration.rb:1455:in `each'
  from C:/projects/jekyll-remote-theme/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.7.0/lib/rspec/core/configuration.rb:1455:in `requires='
  from C:/projects/jekyll-remote-theme/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.7.0/lib/rspec/core/configuration_options.rb:112:in `block in process_options_into'
  from C:/projects/jekyll-remote-theme/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.7.0/lib/rspec/core/configuration_options.rb:111:in `each'
  from C:/projects/jekyll-remote-theme/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.7.0/lib/rspec/core/configuration_options.rb:111:in `process_options_into'
  from C:/projects/jekyll-remote-theme/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.7.0/lib/rspec/core/configuration_options.rb:21:in `configure'
  from C:/projects/jekyll-remote-theme/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.7.0/lib/rspec/core/runner.rb:99:in `setup'
  from C:/projects/jekyll-remote-theme/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.7.0/lib/rspec/core/runner.rb:86:in `run'
  from C:/projects/jekyll-remote-theme/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.7.0/lib/rspec/core/runner.rb:71:in `run'
  from C:/projects/jekyll-remote-theme/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.7.0/lib/rspec/core/runner.rb:45:in `invoke'
  from C:/projects/jekyll-remote-theme/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.7.0/exe/rspec:4:in `<top (required)>'
  from C:/projects/jekyll-remote-theme/vendor/bundle/ruby/2.2.0/bin/rspec:23:in `load'
  from C:/projects/jekyll-remote-theme/vendor/bundle/ruby/2.2.0/bin/rspec:23:in `<main>'
Command exited with code 1

**Comment by IlyaFinkelshteyn** [comment]
@ashmaroli can you please send a link to the failed build?

**Comment by ashmaroli** [comment]
[link to failed build](https://ci.appveyor.com/project/ashmaroli/jekyll-remote-theme/build/2)
