### ISSUE TITLE
Push-AppveyorArtifact against relative path which contains backslash fails on Ubuntu

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [appveyor/ci#2574]
Repro YAML:

```
install:
- ps: |
    mkdir anotherfolder
    cd anotherfolder
    test-path ..\README.md
    echo "Absolute path:"
    Push-AppveyorArtifact /home/appveyor/projects/projecta/README.md
    echo "Relative path forward slash:"
    Push-AppveyorArtifact ../README.md
    $error[0]|format-list -force
    echo "Relative path back slash:"
    Push-AppveyorArtifact ..\README.md
    $error[0]|format-list -force
```

Detailed error:

```
Exception             : AppVeyor.BuildAgent.PowerShell.AppVeyorException: Error uploading build artifact. ---> System.IO.FileNotFoundException: File not found: /home/appveyor/projects/projecta/anotherfolder/..\README.md
                           at AppVeyor.BuildAgent.Api.RestBuildServices.AddArtifact(String path, String fileName, String name, Nullable`1 type, String storageType, Nullable`1 size)
                           at AppVeyor.BuildAgent.Utilities.UploadDownloadUtility.UploadArtifact(String path, String fileName, String name, Nullable`1 type, UploadVerbosity verbosity, Action`1 write)
                           at AppVeyor.BuildAgent.PowerShell.PushAppVeyorArtifactCmdlet.ProcessRecord()
                           --- End of inner exception stack trace ---
                           at AppVeyor.BuildAgent.PowerShell.PushAppVeyorArtifactCmdlet.ProcessRecord()
                           at System.Management.Automation.Cmdlet.DoProcessRecord()
                           at System.Management.Automation.CommandProcessor.ProcessRecord()
TargetObject          : 
CategoryInfo          : NotSpecified: (:) [Push-AppVeyorArtifact], AppVeyorException
FullyQualifiedErrorId : AppVeyor.BuildAgent.PowerShell.AppVeyorException,AppVeyor.BuildAgent.PowerShell.PushAppVeyorArtifactCmdlet
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 10
                        at <ScriptBlock>, /opt/appveyor/build-agent/ps-shell.ps1: line 118
PipelineIterationInfo : {}
PSMessageDetails      : 

```

**Comment by HarelM** [comment]
I think this happens on macos too (probably because it's linux under the hood).
Any due date to fixing this?
Also it is not clear what's the workaround.
I have the following build which doesn't upload a file, can you elaborate on the easiest solution?
Does using forward slash fixes this?

**Comment by HarelM** [comment]
Ok, switching to forward slash is the easiest workaround.
