### ISSUE TITLE
Build using conda and numpy/scipy fails on win32 (

### ISSUE THREAD

**Issue by fakufaku** [appveyor/ci#2774]
I have a [build](https://ci.appveyor.com/project/fakufaku/pyroomacoustics) of this [repo](https://github.com/LCAV/pyroomacoustics) that uses `miniconda` on `win32` that fails when `scipy` (`fftpack`) is loaded during the tests. Everything works fine on `win64`.

The [full log](](https://ci.appveyor.com/project/fakufaku/pyroomacoustics/builds/21002032/job/owp46wqr6xua0ne8) and the final error below.
```
======================================================================
ERROR: Failure: ImportError (DLL load failed: %1 is not a valid Win32 application.)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda3\envs\test-environment\lib\site-packages\nose\failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "C:\Miniconda3\envs\test-environment\lib\site-packages\nose\loader.py", line 417, in loadTestsFromName
    addr.filename, addr.module)
  File "C:\Miniconda3\envs\test-environment\lib\site-packages\nose\importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "C:\Miniconda3\envs\test-environment\lib\site-packages\nose\importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "C:\Miniconda3\envs\test-environment\lib\imp.py", line 245, in load_module
    return load_package(name, filename)
  File "C:\Miniconda3\envs\test-environment\lib\imp.py", line 217, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 697, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\projects\pyroomacoustics\pyroomacoustics\__init__.py", line 117, in <module>
    from .room import *
  File "C:\projects\pyroomacoustics\pyroomacoustics\room.py", line 274, in <module>
    from . import beamforming as bf
  File "C:\projects\pyroomacoustics\pyroomacoustics\beamforming.py", line 11, in <module>
    from . import utilities as u
  File "C:\projects\pyroomacoustics\pyroomacoustics\utilities.py", line 6, in <module>
    from scipy import signal
  File "C:\Miniconda3\envs\test-environment\lib\site-packages\scipy\signal\__init__.py", line 311, in <module>
    from . import sigtools, windows
  File "C:\Miniconda3\envs\test-environment\lib\site-packages\scipy\signal\windows\__init__.py", line 40, in <module>
    from .windows import *
  File "C:\Miniconda3\envs\test-environment\lib\site-packages\scipy\signal\windows\windows.py", line 9, in <module>
    from scipy import fftpack, linalg, special
  File "C:\Miniconda3\envs\test-environment\lib\site-packages\scipy\fftpack\__init__.py", line 99, in <module>
    from .basic import *
  File "C:\Miniconda3\envs\test-environment\lib\site-packages\scipy\fftpack\basic.py", line 12, in <module>
    from . import _fftpack
ImportError: DLL load failed: %1 is not a valid Win32 application.
----------------------------------------------------------------------
Ran 1 test in 0.461s
``` 

The YaML config file
```
build: false

environment:
  matrix:
    - PYTHON_VERSION: 3.5
      MINICONDA: C:\Miniconda3
      RESTORE_MINICONDA: C:\Miniconda35
      PYTHON_ARCH: "32"
    - PYTHON_VERSION: 3.5
      MINICONDA: C:\Miniconda3-x64
      RESTORE_MINICONDA: C:\Miniconda35-x64
      PYTHON_ARCH: "64"
    - PYTHON_VERSION: 3.6
      MINICONDA: C:\Miniconda3
      RESTORE_MINICONDA: C:\Miniconda36
      PYTHON_ARCH: "32"
    - PYTHON_VERSION: 3.6
      MINICONDA: C:\Miniconda3-x64
      RESTORE_MINICONDA: C:\Miniconda36-x64
      PYTHON_ARCH: "64"

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - "conda create -q -n test-environment python=%PYTHON_VERSION% numpy scipy>=0.18.0 matplotlib nose"
  - activate test-environment

  - pip install -r requirements.txt
  - python setup.py install

test_script:
  - nosetests
  - python.exe setup.py build_ext --inplace
  - python pyroomacoustics/c_package/tests/check_build.py
  - nosetests

after_test:
  # This step builds your wheels.
  - python.exe setup.py bdist_wheel

artifacts:
  # bdist_wheel puts your built wheel in the dist directory
  - path: dist\*.whl

notifications:
  - provider: Slack
    incoming_webhook:
secure: nqOk3aT2OywRUWp1LQ2geV/UcGqrz1wN/q24xrrNI8HsNX2HGit3psyMvzS4taPzB4fzNFdOMHHoyqbruc4lpqOr1PWql5PVwpq1K46L8Bw=
```

**Comment by fakufaku** [comment]
This issue seems resolved now. Sorry for the noise.

**Comment by IlyaFinkelshteyn** [comment]
Thanks for the update! Just recently scratched my head looking into it :)

**Comment by fakufaku** [comment]
Not sure why that happened. I just re-run the build after a few days without changing anything and it finished without problems... ¯\_(ツ)_/¯
