### ISSUE TITLE
BuildAgent exception on msbuild step: Unable to create a new user process

### ISSUE THREAD

**Issue by cshorler** [appveyor/ci#3203]
test project:
https://ci.appveyor.com/project/cshorler/stepcode-m6l8m

monologue:
https://help.appveyor.com/discussions/problems/25312-unable-to-create-a-new-user-process

Build agent event log extract below (full exception in event 74)
```
Event number                    : 73
Written time                    : Nov 10, 2019 20:41:14.974657700 UTC
Event level                     : Information (4)
Computer name                   : appveyor-vm
Source name                     : AppVeyor Build Agent
Event identifier                : 0x00000000 (0)
Number of strings               : 1
String: 1                       : Run CMD: msbuild "C:\projects\stepcode-m6l8m\build\SC.sln" /verbosity:normal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

Event number                    : 74
Written time                    : Nov 10, 2019 20:41:14.974657700 UTC
Event level                     : Error (2)
Computer name                   : appveyor-vm
Source name                     : AppVeyor Build Agent
Event identifier                : 0x00000000 (0)
Number of strings               : 1
String: 1                       : Build exception: System.ComponentModel.Win32Exception (0x80004005): Unable to create a new user process.
   at Appveyor.Utilities.ExternalProcess.Start(String commandLine, String workingDirectory, Boolean redirectStdErr, Action`1 consoleWrite, Dictionary`2 environmentVariables)
   at Appveyor.Utilities.ExternalProcess.ThreadedStart(Object obj)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Appveyor.BuildAgent.BuildRunner.<RunScript>d__74.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Appveyor.BuildAgent.BuildRunner.<Build>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Appveyor.BuildAgent.BuildRunner.<StartAsync>d__16.MoveNext()
```

Monitoring the build agent with Procmon shows this file system error - only speculation without source code as to whether a type error could be the cause of a number of other errors, including the failure to execute msbuild.  Seems unlikely
`3:53:05.5127205 PM	Appveyor.BuildAgent.Interactive.exe	4020	QueryOpen	C:\Windows\system32\Microsoft.PowerShell.Core\FileSystem::C:\projects\stepcode-m6l8m\build	NAME INVALID`

**Comment by cshorler** [comment]
still happening today.

Can anyone help me here?

**Comment by FeodorFitsner** [comment]
We still can't reproduce the issue, sorry.
