### ISSUE TITLE
Appveyor.NUnit3Logger.dll does not support running tests under net20 and net35

### ISSUE THREAD

**Issue by ig-sinicyn** [appveyor/ci#3412]
Failing build:
https://ci.appveyor.com/project/andrewvk/codejam/builds/32580761

Nunit log:
```
12:51:40.231 Error [ 1] ServiceManager: NUnit.Engine.NUnitEngineException: Extension C:\Tools\NUnit3\addins\Appveyor.NUnit3Logger.dll targets v4.0, which is not available.
   at NUnit.Engine.Services.ExtensionService.FindExtensionsInAssembly(ExtensionAssembly assembly)
   at NUnit.Engine.Services.ExtensionService.StartService()
   at NUnit.Engine.Services.ServiceManager.StartServices()
```

**How to reproduce:**

Command:
```
PS C:\projects\codejam\CodeJam.Main.Tests\bin\Release\net20> nunit3-console.exe .\CodeJam.Tests.dll --trace=Verbose
NUnit Console Runner 3.11.1 (.NET 2.0)
Copyright (c) 2020 Charlie Poole, Rob Prouse
Friday, May 1, 2020 12:51:39 PM

Runtime Environment
   OS Version: Microsoft Windows NT 6.2.9200.0
   Runtime: .NET Framework CLR v4.0.30319.42000

Test Files
    .\CodeJam.Tests.dll


Unhandled Exception: NUnit.Engine.NUnitEngineException: Remote test agent exited with non-zero exit code -532459699
   at NUnit.Engine.Services.TestAgency.OnAgentExit(Process process, Guid agentId) in C:\Users\Chris\Documents\git\nunit-console\src\NUnitEngine\nunit.engine\Services\TestAgency.cs:line 260
   at NUnit.Engine.Services.TestAgency.<>c__DisplayClass7_0.<LaunchAgentProcess>b__0(Object sender, EventArgs e) in C:\Users\Chris\Documents\git\nunit-console\src\NUnitEngine\nunit.engine\Services\TestAgency.cs:line 149
   at System.Diagnostics.Process.OnExited()
   at System.Diagnostics.Process.RaiseOnExited()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading._ThreadPoolWaitOrTimerCallback.PerformWaitOrTimerCallback(Object state, Boolean timedOut)

Errors, Failures and Warnings

1) Error :
NUnit.Engine.NUnitEngineException : Unable to acquire remote process agent
--NUnitEngineException
Unable to acquire remote process agent
   at NUnit.Engine.Runners.ProcessRunner.CreateAgentAndRunner() in C:\Users\Chris\Documents\git\nunit-console\src\NUnitEngine\nunit.engine\Runners\ProcessRunner.cs:line 315
   at NUnit.Engine.Runners.ProcessRunner.RunTests(ITestEventListener listener, TestFilter filter) in C:\Users\Chris\Documents\git\nunit-console\src\NUnitEngine\nunit.engine\Runners\ProcessRunner.cs:line 163

Test Run Summary
  Overall result: Failed
  Test Count: 0, Passed: 0, Failed: 0, Warnings: 0, Inconclusive: 0, Skipped: 0
  Start time: 2020-05-01 12:51:39Z
    End time: 2020-05-01 12:51:40Z
    Duration: 0.485 seconds

Results (nunit3) saved as TestResult.xml
```

output in agent trace file:
```
InternalTrace: Initializing at level Debug
12:51:40.075 Info  [ 1] NUnitTestAgent: Agent process 3052 starting
12:51:40.075 Info  [ 1] NUnitTestAgent: Running under version 2.0.50727.9043, .NET 3.5
12:51:40.075 Debug [ 1] NUnitTestAgent: Agent process has the COMPLUS_Version environment variable value "NULL" overridden with "v2.0.50727", restoring the original value.
12:51:40.075 Debug [ 1] ServiceManager: Added ExtensionService
12:51:40.090 Debug [ 1] ServiceManager: Added DomainManager
12:51:40.090 Debug [ 1] ServiceManager: Added InProcessTestRunnerFactory
12:51:40.090 Debug [ 1] ServiceManager: Added DriverService
12:51:40.090 Info  [ 1] NUnitTestAgent: Initializing Services
12:51:40.090 Info  [ 1] ServiceManager: Initializing ExtensionService
12:51:40.090 Info  [ 1] ExtensionService: Scanning nunit.engine.core assembly for extension points
12:51:40.090 Info  [ 1] ExtensionService:   Found Path=/NUnit/Engine/NUnitV2Driver, Type=NUnit.Engine.Extensibility.IFrameworkDriver
12:51:40.106 Info  [ 1] ExtensionService: Scanning nunit.engine.api assembly for extension points
12:51:40.106 Info  [ 1] ExtensionService:   Found Path=/NUnit/Engine/TypeExtensions/IService, Type=NUnit.Engine.IService
12:51:40.106 Info  [ 1] ExtensionService:   Found Path=/NUnit/Engine/TypeExtensions/ITestEventListener, Type=NUnit.Engine.ITestEventListener
12:51:40.106 Info  [ 1] ExtensionService:   Found Path=/NUnit/Engine/TypeExtensions/IDriverFactory, Type=NUnit.Engine.Extensibility.IDriverFactory
12:51:40.106 Info  [ 1] ExtensionService:   Found Path=/NUnit/Engine/TypeExtensions/IProjectLoader, Type=NUnit.Engine.Extensibility.IProjectLoader
12:51:40.106 Info  [ 1] ExtensionService:   Found Path=/NUnit/Engine/TypeExtensions/IResultWriter, Type=NUnit.Engine.Extensibility.IResultWriter
12:51:40.106 Info  [ 1] ExtensionService: Processing file C:\Tools\NUnit3\appveyor.addins
12:51:40.153 Info  [ 1] ExtensionService: Processing file C:\Tools\NUnit3\nunit.bundle.addins
12:51:40.168 Info  [ 1] ExtensionService: Scanning C:\Tools\NUnit3\addins\Appveyor.NUnit3Logger.dll assembly for Extensions
12:51:40.231 Error [ 1] ServiceManager: Failed to initialize ExtensionService
12:51:40.231 Error [ 1] ServiceManager: NUnit.Engine.NUnitEngineException: Extension C:\Tools\NUnit3\addins\Appveyor.NUnit3Logger.dll targets v4.0, which is not available.
   at NUnit.Engine.Services.ExtensionService.FindExtensionsInAssembly(ExtensionAssembly assembly)
   at NUnit.Engine.Services.ExtensionService.StartService()
   at NUnit.Engine.Services.ServiceManager.StartServices()
```

**Comment by ChrisMaddock** [comment]
Thanks for filing an issue over at NUnit, @ig-sinicyn.

For any other user's finding this issue, two potential workarounds:

1. If you would be happy to temporarily run your tests on the v4 CLR rather than v2, pass the --framework=net4.0 flag to force that. That should allow everything to run happily on the v4 CLR.

2. Alternatively, delete the file C:\Tools\NUnit3\appveyor.addins on each appveyor run.

@team-appveyor: This is a bug on our side, but it's not new behaviour, and I'm interested to know why it's only come to light now. Has Appveyor.NUnit3Logger.dll recently been upgraded to net4x? Or is it just that nobodies tried to run .NET 2.0/.NET 3.5 on appveyors default-install test runner before? (NUnit runs it's own .NET2.0 test on Appveyor, but we install the console ourselves, so wouldn't be affected.)

**Comment by FeodorFitsner** [comment]
It's, actually, NUnit Console runner was bumped 2 weeks ago from 3.9 to 3.11: https://github.com/appveyor/build-images/commit/54561b4cd83ac0f9a8e149579e54ca206dc02e15#diff-a277d40af0ff9ec80d4c5ced4f9e2e81

@ChrisMaddock Was it working before?

**Comment by ChrisMaddock** [comment]
Thanks @FeodorFitsner. That's surprising. Nothing's changed that would affect this by my memory, but also, 3.9 was released nearly 2 years ago - so I may well be wrong! 😅 @ig-sinicyn - is this something that's started failing recently, or something you've just tried to set up now?

**Comment by ig-sinicyn** [comment]
We've start seeing the issue on Apr, 20, here's [a build history](https://ci.appveyor.com/project/andrewvk/codejam/history). It was not investigated until now as local tests were fine and for our project net20 targeting is more nice-to-have feature than a real thing.

**Comment by ChrisMaddock** [comment]
Thanks @ig-sinicyn. We'll have to take a dig.

**Comment by FeodorFitsner** [comment]
@ChrisMaddock Thanks for looking into that!

@ig-sinicyn You can install NUnit Console runner 3.9 during the build using the following code in `appveyor.yml`:

```yaml
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/build-images/21d2405c7a91118b53484d9605061329b88d81c5/scripts/Windows/install_nunit3.ps1'))
```

Wondering 3.9 runner fixes your issue.

**Comment by ig-sinicyn** [comment]
@FeodorFitsner, the 3.9 runner has no issues with net20/net35 tests. Thanks for letting me know about the installation script!

**Comment by ChrisMaddock** [comment]
My only worry about using the 3.9 runner, is that I thing it might have a bug where it's actually running your .NET 2.0 tests on .NET 4.0 - which is why _this_ particular bug isn't visible! I'm not 100% sure, and haven't had the chance to check, but the agent logs should tell you. 🙂

**Comment by ig-sinicyn** [comment]
@ChrisMaddock 

Yep, the tests are running on net4.0. Not a big issue for us as we have local tests to troubleshoot targeting-related things.

**Comment by ChrisMaddock** [comment]
Thanks for confirming @ig-sinicyn. We'll hopefully get it fixed up sometime soon...

**Comment by theraot** [comment]
"sometime soon"

Any workround?

**Comment by ChrisMaddock** [comment]
@FeodorFitsner - this should be fixed in the latest version of the NUnit Console. Would you be able to update the version on Appveyor? Thanks! 🙂

**Comment by FeodorFitsner** [comment]
Absolutely, thanks for letting know!

**Comment by NN---** [comment]
Works well.
Thanks.
