### ISSUE TITLE
Appveyor OnPremise: Retention Policy not working

### ISSUE THREAD

**Issue by itniels** [appveyor/ci#3433]
### **Environment Information**
AppVeyor: `v7.0.2546`
OS: `Ubuntu 18.04.3 LTS`
Cores: `2`
RAM: `4 GB`
Disk: NVMe SSD 40 GB
Build Image: `Based on “appveyor/build-image:minimal-ubuntu-18.04”`

### **Issue Description**
Just noticed my server was running low on disk space!

I had set an `Account retention policy` to 14 days.
But it seems not a single build has been cleaned up!

I then tried to set one on a project itself, and this also does not cleanup.
And now i cannot set the project level policy back to the `Account retention policy`, i simply get a 400 error and a blank red toast notification.

**UI error:**
![image](https://user-images.githubusercontent.com/15611687/82121254-e5362280-978b-11ea-90d5-5c924255de14.png)

**Console error:**
![image](https://user-images.githubusercontent.com/15611687/82121293-2b8b8180-978c-11ea-846e-b8413c42e057.png)

**Request preview:**
![image](https://user-images.githubusercontent.com/15611687/82121337-8624dd80-978c-11ea-892e-35c35f31dd33.png)

### **Steps to reproduce (Retention not working)**
1) Set an account retention for n days
nothing will get cleaned up.

### **Steps to reproduce (failure to set retention)**
1) Open a project
2) Goto project settings
3) Goto Retention policy
4) Set retention to `Project retention policy` and click Update policy
5) Set retention to `Apply account retention policy` and click Update policy

A blank error will now show with a 400 error in the console.

**Comment by FeodorFitsner** [comment]
Could you please try upgrading to the latest 7.0.2885 build (not public yet) fixing this (and other) issue.

[Backup AppVeyor Server installation first!](https://www.appveyor.com/docs/server/maintenance/#linux)

Then upgrade:

```bash
wget https://appveyordownloads.blob.core.windows.net/appveyor/7.0.2885/appveyor-server_7.0.2885_amd64.deb
dpkg -i appveyor-server_7.0.2885_amd64.deb
```

Also, make sure you have configured a scheduled task for running retention policy: https://www.appveyor.com/docs/server/configuration/#builds-retention-policy

**Comment by itniels** [comment]
Thank you so much @FeodorFitsner 
I have tried it now :) 
I had NOT setup the cronjob.. i never made the connection that retention policy required these!

After running both tasks, only a small sum was cleaned up.
The first task seemed to have failed with the following stacktrace

![image](https://user-images.githubusercontent.com/15611687/82340072-19f5e400-99ef-11ea-8909-03f359416fd3.png)

```
System.InvalidOperationException: The LINQ expression 'DbSet<Build>
    .Where(b => b.ProjectId == __8__locals1_projectId_0 && b.IsDeleted == False && b.Created < __p_1)' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.<VisitMethodCall>g__CheckTranslated|8_0(ShapedQueryExpression translated, <>c__DisplayClass8_0& )
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Appveyor.ScheduleJobs.ExecuteRetentionPolicy.ApplyRetentionToProject(Int32 projectId, Int32 daysOld, Boolean exceptNugetBuilds, Boolean exceptDeployedBuilds, String exceptBranchBuilds, String exceptTagBuilds, String exceptBuildsWithMessage, Int32 buildsPageSize)
   at Appveyor.ScheduleJobs.ExecuteRetentionPolicy.ExecuteAccountPolicies(Int32 policiesPageSize, Int32 projectsPageSize, Int32 buildsPageSize) in /home/appveyor/projects/appveyor/Appveyor/ScheduleJobs/ExecuteRetentionPolicy.cs:line 147
   at Appveyor.ScheduleJobs.ExecuteRetentionPolicy.Run(Int32 scheduleId, Int32 runId, IDictionary`2 parameters, CancellationToken cancellationToken) in /home/appveyor/projects/appveyor/Appveyor/ScheduleJobs/ExecuteRetentionPolicy.cs:line 68
   at Appveyor.Services.Scheduler.<>c__DisplayClass15_0.<<ProcessScheduleMessage>b__0>d.MoveNext() in /home/appveyor/projects/appveyor/Appveyor/Services/Scheduler.cs:line 192
```

**Comment by itniels** [comment]
Just pinging this too see if there is anything in the works?
As I just got reminded that nothing is cleaned up 🙈

`Error uploading artifact the storage: No space left on device`
Also slight spelling mistake in that line 🙂

**Comment by FeodorFitsner** [comment]
Have you tried the latest version yet? https://appveyordownloads.blob.core.windows.net/appveyor/7.0.2973/appveyor-server_7.0.2973_amd64.deb

**Comment by itniels** [comment]
Ohh i hadn't seen a new version was out! 
so sorry @FeodorFitsner!

I am on the one you gave me last: `7.0.2954`
I will give this a try and report back!

**Comment by itniels** [comment]
I tried again @FeodorFitsner, 
when running the `ExecuteRetentionPolicy` it throws the same exception as above still unfortunately.

**Comment by FeodorFitsner** [comment]
Alright, we've been able to reproduce the issue on SQLite provider. Here is the build with the fix: https://appveyordownloads.blob.core.windows.net/appveyor/7.0.2974/appveyor-server_7.0.2974_amd64.deb

**Comment by itniels** [comment]
Awesome @FeodorFitsner 🙌

The ExecuteRetentionPolicy worked!
![image](https://user-images.githubusercontent.com/15611687/101734649-eaa8e080-3ac0-11eb-8327-bcd3e8e704c8.png)

Getting some free space now 😊
![image](https://user-images.githubusercontent.com/15611687/101736962-7c661d00-3ac4-11eb-962f-e991aeedd8a1.png)


Thankyou so much!
