### ISSUE TITLE
Build fails with Gradle 6.4.1 (UnknownModuleException)

### ISSUE THREAD

**Issue by marandaneto** [appveyor/ci#3437]
**Stack trace:**
org.gradle.api.internal.classpath.UnknownModuleException: Cannot locate JAR for module 'ant' in classpath: [C:\Users\appveyor\.gradle\wrapper\dists\gradle-6.4.1-all\13imxtezgn9nwzqt8rgtkunh1\gradle-6.4.1\lib\gradle-launcher-6.4.1.jar, C:\Users\appveyor\.gradle\wrapper\dists\gradle-6.4.1-all\13imxtezgn9nwzqt8rgtkunh1\gradle-6.4.1\lib\gradle-bootstrap-6.4.1.jar, C:\Users\appveyor\.gradle\wrapper\dists\gradle-6.4.1-all\13imxtezgn9nwzqt8rgtkunh1\gradle-6.4.1\lib\gradle-base-services-6.4.1.jar, C:\Users\appveyor\.gradle\wrapper\dists\gradle-6.4.1-all\13imxtezgn9nwzqt8rgtkunh1\gradle-6.4.1\lib\gradle-core-api-6.4.1.jar, C:\Users\appveyor\.gradle\wrapper\dists\gradle-6.4.1-all\13imxtezgn9nwzqt8rgtkunh1\gradle-6.4.1\lib\gradle-core-6.4.1.jar].
	at org.gradle.api.internal.classpath.DefaultModuleRegistry.loadExternalModule(DefaultModuleRegistry.java:106)
	at org.gradle.api.internal.classpath.DefaultModuleRegistry.getExternalModule(DefaultModuleRegistry.java:96)
	at org.gradle.api.internal.DefaultClassPathProvider.findClassPath(DefaultClassPathProvider.java:63)
	at org.gradle.api.internal.DefaultClassPathRegistry.getClassPath(DefaultClassPathRegistry.java:35)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:48)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:35)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:108)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)
Command exited with code 1

**Configuration:**
https://github.com/getsentry/sentry-android/blob/master/.appveyor.yml

**Steps to reproduce:**
Pretty much upgrading Gradle to 6.4.1, < 6.4 works just fine.
Gradle 6.4.1 works with other CI tools and also locally, so it's either a problem with Appveyor or Gradle on Windows, not sure.

Let me know if you need any more info.

Keep the great work, thanks :)

**Comment by marandaneto** [comment]
update: it's an issue with `cache: %USERPROFILE%\\.gradle\\wrapper`

Context: https://github.com/gradle/gradle/issues/13157

**Comment by FeodorFitsner** [comment]
If the contents of `wrapper` folder is "non-cacheable" then just remove cache for it? Cache doesn't work for all cases, obviously, there are situations sometimes where certain file attributes or timestamps are essential.

**Comment by Nathan187** [comment]
anyone has an idea why this error occurs?
