### ISSUE TITLE
Python 3.9 on Ubuntu images

### ISSUE THREAD

**Issue by pavel-kirienko** [appveyor/ci#3570]
This is not a duplicate of #3541.

Currently, Python 3.9 is only available on Windows images. Ubuntu images still run Python 3.9-alpha, which is crashed by NumPy:

```
$ python --version
Python 3.9.0a6
$ pip install numpy
<snip...>
$ python -c "import numpy"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/appveyor/venv3.9.0/lib/python3.9/site-packages/numpy/__init__.py", line 151, in <module>
    from . import random
  File "/home/appveyor/venv3.9.0/lib/python3.9/site-packages/numpy/random/__init__.py", line 179, in <module>
    from . import _pickle
  File "/home/appveyor/venv3.9.0/lib/python3.9/site-packages/numpy/random/_pickle.py", line 1, in <module>
    from .mtrand import RandomState
ImportError: /home/appveyor/venv3.9.0/lib/python3.9/site-packages/numpy/random/mtrand.cpython-39-x86_64-linux-gnu.so: undefined symbol: PyCMethod_New
```

MWE: https://ci.appveyor.com/project/Zubax/ci-evaluation/builds/36312028

**Comment by FeodorFitsner** [comment]
We are working on Ubuntu images update.

**Comment by pavel-kirienko** [comment]
@FeodorFitsner Thanks. Do you have an ETA?

**Comment by FeodorFitsner** [comment]
Tomorrow or early next week.
