### ISSUE TITLE
Pester 5 tests fail in the AppVeyor CI but run OK on the VM

### ISSUE THREAD

**Issue by marcingminski** [appveyor/ci#3674]
The CI returns:
```
[-] Discovery in C:\projects\sqlwatch\SqlWatch.Test\Pester.SqlWatch.Test.Checks.p5.ps1 failed with:
System.IO.FileLoadException: Mixed mode assembly is built against version 'v2.0.50727' of the runtime and cannot be loaded in the 4.0 runtime without additional configuration information.
   at Microsoft.SqlServer.Management.PowerShell.GetScriptCommand.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
at <ScriptBlock>, C:\projects\sqlwatch\SqlWatch.Test\Pester.SqlWatch.Test.Checks.p5.ps1: line 12
at BeforeDiscovery, C:\Users\appveyor\Documents\WindowsPowerShell\Modules\Pester\5.2.0\Pester.psm1: line 5645
at <ScriptBlock>, C:\projects\sqlwatch\SqlWatch.Test\Pester.SqlWatch.Test.Checks.p5.ps1: line 7
at <ScriptBlock>, C:\Users\appveyor\Documents\WindowsPowerShell\Modules\Pester\5.2.0\Pester.psm1: line 2959
at Invoke-File, C:\Users\appveyor\Documents\WindowsPowerShell\Modules\Pester\5.2.0\Pester.psm1: line 2968
at Invoke-BlockContainer, C:\Users\appveyor\Documents\WindowsPowerShell\Modules\Pester\5.2.0\Pester.psm1: line 2883
at Discover-Test, C:\Users\appveyor\Documents\WindowsPowerShell\Modules\Pester\5.2.0\Pester.psm1: line 1442
at Invoke-Test, C:\Users\appveyor\Documents\WindowsPowerShell\Modules\Pester\5.2.0\Pester.psm1: line 2403
at Invoke-Pester<End>, C:\Users\appveyor\Documents\WindowsPowerShell\Modules\Pester\5.2.0\Pester.psm1: line 5088
at <ScriptBlock>, <No file>: line 35
```
The tests are invoked via the Test tabs, not via yml with the following code:
```
$containers = @(
    ( New-PesterContainer -Path $TestFiles.FullName -Data @{ SqlInstance = "localhost\SQL2017"; SqlWatchDatabase = $SqlWatchDatabase } )
    ( New-PesterContainer -Path $TestFiles.FullName -Data @{ SqlInstance = "localhost\SQL2016"; SqlWatchDatabase = $SqlWatchDatabase } )
    ( New-PesterContainer -Path $TestFiles.FullName -Data @{ SqlInstance = "localhost\SQL2014"; SqlWatchDatabase = $SqlWatchDatabase } )
    ( New-PesterContainer -Path $TestFiles.FullName -Data @{ SqlInstance = "localhost\SQL2012SP1"; SqlWatchDatabase = $SqlWatchDatabase } )
)
Invoke-Pester -Container $containers -Output Detailed -CI
```
The same tests, invoked in the same manner run OK when I log in to the AppVeyor VM and execute the following in the PowerShelll IDE:

```
$containers = @(
    ( New-PesterContainer -Path $TestFiles.FullName -Data @{ SqlInstance = "localhost\SQL2017"; SqlWatchDatabase = $SqlWatchDatabase } )
    ( New-PesterContainer -Path $TestFiles.FullName -Data @{ SqlInstance = "localhost\SQL2016"; SqlWatchDatabase = $SqlWatchDatabase } )
    ( New-PesterContainer -Path $TestFiles.FullName -Data @{ SqlInstance = "localhost\SQL2014"; SqlWatchDatabase = $SqlWatchDatabase } )
    ( New-PesterContainer -Path $TestFiles.FullName -Data @{ SqlInstance = "localhost\SQL2012SP1"; SqlWatchDatabase = $SqlWatchDatabase } )
)
Invoke-Pester -Container $containers -Output Detailed -CI
```

**Comment by marcingminski** [comment]
Interestingly, when I run `Invoke-SqlCmd` as a PS Job, it executes ok. I suppose it's because it is then brand-new PS background session
![image](https://user-images.githubusercontent.com/8288333/117543862-83af3980-b016-11eb-946e-af8bb8d585c2.png)

So, for those you are having the same problem, run your stuff as background jobs.

**Comment by FeodorFitsner** [comment]
AppVeyor Build Agent is a .NET Framework app which hosts its own PowerShell host. `Invoke-SqlCmd` cmdlet references conflict with build agent assembly references. The same issue exists for AWS management cmdlet.

Workaround is to run via `- cmd: powershell <your-script.ps1>` or like you did in a separate Job which is also a new `powershell.exe` process.

**Comment by marcingminski** [comment]
Thank you. Would be good if this was documented somewhere. Apologies if it is but I did not find it. The error is not clear enough to understand what needs to happen. Took me a bit of tinkering to work it out.  
The .NET app can apparently be set to be able to run mixed mode: https://github.com/PowerShell/vscode-powershell/issues/232
