### ISSUE TITLE
(most likely) outdated PSReadLine version used on CI 

### ISSUE THREAD

**Issue by zhiburt** [appveyor/ci#3727]
https://github.com/PowerShell/PSReadLine/issues/2822

https://ci.appveyor.com/project/zhiburt/expectrl/builds/40658505/job/qra7ilb9m6wafjel

**Comment by FeodorFitsner** [comment]
We are not explicitly installing PSReadLine into build images. Is it part of something else, could you please elaborate?

**Comment by zhiburt** [comment]
I could imagine this is a part of default Powershell package

> If you are using Windows PowerShell on Windows 10 or using PowerShell 6+, PSReadLine is already installed. Windows PowerShell on the latest Windows 10 has version 2.0.0-beta2 of PSReadLine. PowerShell 6+ versions have the newer prerelease versions of PSReadLine.
*taken from a PSReadLine repo*

**Comment by zhiburt** [comment]
And

> PSReadLine 2.1.0 ships with PowerShell 7.1 and is supported in all supported versions of PowerShell. It is available to install from the PowerShell Gallery. To install PSReadLine 2.1.0 in a supported version of PowerShell run the following command.

On the reference PR was said that 2.1.0 should not have this issue.

So I am guessing the issue in version of `pwsh` you have?

**Comment by FeodorFitsner** [comment]
I'm not sure what your tests are doing, but at least they run on `Visual Studio 2019` image which has the latest Windows PowerShell 5.x (as it's based on Windows Server 2019 OS) and the latest version of PowerShell Core 7.1.4. Could you do a simple, isolated repro?

**Comment by binki** [comment]
```yaml
image:
  - Visual Studio 2026
build_script:
  - cmd: 'ECHO ECHO hi | powershell -noprofile -'
```
I get this output:
```
ECHO ECHO hi | powershell -noprofile -
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 0 Keys:
Exception:
System.IO.IOException: The handle is invalid.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at Microsoft.PowerShell.Internal.VirtualTerminal.get_BufferWidth()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
hi
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 0 Keys:
Exception:
System.IO.IOException: The handle is invalid.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at Microsoft.PowerShell.Internal.VirtualTerminal.get_BufferWidth()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
Discovering tests...OK
Build success
```
It looks like the error doesn’t actually affect operation, but it is weird that using powershell at all on appveyor always prints this error.

**Comment by binki** [comment]
Actually, this output is not harmless. The messages are printed by powershell on the standard output stream. This means that when I use the powershell’s output (e.g., by doing something like `ECHO ECHO $((New-Guid).ToString("B").ToUpperInvariant()) | powershell -noprofile ->guid.vs || EXIT /B 1` followed by `SET /p guid=<guid.vs`), the error message printed by powershell is intermingled with the actual script output, preventing the powershell output from being read correctly.

My current workaround is to use `Out-File` like `ECHO ECHO $((New-Guid).ToString("B").ToUpperInvariant()) ^^^| Out-File -Encoding ASCII g.vs | powershell -noprofile - || EXIT /B 1`.

To avoid hard-to-debug failures in user-authored scripts which rely on powershell, I recommend ensuring that each command is invoked in a way which provides a (possibly fake) console.

I know that you are trying to prevent scripts from hanging on waiting on user input. Adding a console might cause some commands to try to read user input and hang which would be a regression. Maybe there is a way to fake out a console just enough so that the powershell error messages don’t print while still signalling to apps not to try to read user input.
