### ISSUE TITLE
BYOC Azure Cannot convert 'System.Object[]' to the type 'System.String'

### ISSUE THREAD

**Issue by marcingminski** [appveyor/ci#3772]
Running the following on Azure Windows Server 2019 VM:

```
Connect-AppVeyorToAzure -AppVeyorUrl https://ci.appveyor.com -ApiToken xxx -Location "UK South" -VmSize Standard_B2ms -ImageName "Windows" -ImageOs "Windows" -ImageTemplate "minimal-windows-server.json" -ImageFeatures "" -ImageCustomScript "" -ImageCustomScriptAfterReboot ""
```

results in:

```
 Connect-AppVeyorToAzure : Cannot convert 'System.Object[]' to the type 'System.String' required by parameter 'Destination'. Specified method is not supported.
At line:1 char:1
+ Connect-AppVeyorToAzure -AppVeyorUrl https://ci.appveyor.com -ApiToke ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Connect-AppVeyorToAzure], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgument,Connect-AppVeyorToAzure 
```

I followed step by step as in https://ci.appveyor.com/build-clouds/wizard

**Comment by FeodorFitsner** [comment]
Could you please try running the same command again?

**Comment by marcingminski** [comment]
Same outcome:
![image](https://user-images.githubusercontent.com/8288333/148785264-4288eeeb-48b4-4ea1-b5ff-c1e326baafc1.png)

**Comment by FeodorFitsner** [comment]
OK, could you please enable [PS Transcript](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.host/start-transcript?view=powershell-7.2) to find out the exact place/command of that error and let me know?

**Comment by marcingminski** [comment]
There you go:

```
**********************
Windows PowerShell transcript start
Start time: 20220112225159
Username: appveyor\localadmin
RunAs User: appveyor\localadmin
Configuration Name: 
Machine: appveyor (Microsoft Windows NT 10.0.17763.0)
Host Application: C:\Windows\System32\WindowsPowerShell\v1.0\powershell_ise.exe
Process ID: 9040
PSVersion: 5.1.17763.2268
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.17763.2268
BuildVersion: 10.0.17763.2268
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Transcript started, output file is C:\Users\localadmin\Documents\PowerShell_transcript.appveyor.FEbPpCqm.20220112225159.txt

Checking AppVeyor API access...

Checking if Az PowerShell Module is installed...
PS>TerminatingError(Copy-Item): "Cannot convert 'System.Object[]' to the type 'System.String' required by parameter 'Destination'. Specified method is not supported."
>> TerminatingError(Copy-Item): "Cannot convert 'System.Object[]' to the type 'System.String' required by parameter 'Destination'. Specified method is not supported."
>> TerminatingError(Connect-AppVeyorToAzure): "Cannot convert 'System.Object[]' to the type 'System.String' required by parameter 'Destination'. Specified method is not supported."
Connect-AppVeyorToAzure : Cannot convert 'System.Object[]' to the type 'System.String' required by parameter 
'Destination'. Specified method is not supported.
At line:5 char:1
+ Connect-AppVeyorToAzure -AppVeyorUrl https://ci.appveyor.com -ApiToke ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Connect-AppVeyorToAzure], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgument,Connect-AppVeyorToAzure
Connect-AppVeyorToAzure : Cannot convert 'System.Object[]' to the type 'System.String' required by parameter 'Destination'. Specified method is not supported.
At line:5 char:1
+ Connect-AppVeyorToAzure -AppVeyorUrl https://ci.appveyor.com -ApiToke ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Connect-AppVeyorToAzure], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgument,Connect-AppVeyorToAzure

**********************
Windows PowerShell transcript end
End time: 20220112225228
**********************
```

However, after re-trying multiple times it eventually worked, asked to authenticate to Azure but then failed with lots of warnings and finally an error:

```
 Getting or creating Azure AD service principal ...
WARNING: We have migrated the API calls for this cmdlet from Azure Active Directory Graph to Microsoft Graph.
Visit https://go.microsoft.com/fwlink/?linkid=2181475 for any permission issues.
WARNING: Command exited with error: System.Management.Automation.MethodInvocationException: Exception calling "SecureStringToBSTR" with "1" argument(s): "Value cannot be null.
Parameter name: s" ---> System.ArgumentNullException: Value cannot be null.
Parameter name: s
   at System.Runtime.InteropServices.Marshal.SecureStringToBSTR(SecureString s)
   at CallSite.Target(Closure , CallSite , Type , Object )
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame) 
```
