### ISSUE TITLE
NUnit 3.0

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#498]
Discussion: http://help.appveyor.com/discussions/problems/2586-nunit-3

NUnit sources: https://github.com/nunit/nunit

**Comment by mattiasnordqvist** [comment]
Any workaround while waiting?

**Comment by limanartem** [comment]
For me this worked fine triggreed at "On build finish script"

```
$wc = New-Object 'System.Net.WebClient'
$wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestResult.xml))
```
Also before running build make sure to install nunit3 runner
```
appveyor DownloadFile https://github.com/nunit/nunit/releases/download/3.0.0-beta-3/nunit-3.0.0-beta-3.zip
7z x -oC:\Tools\NUnit3 nunit-3.0.0-beta-3.zip > NUL
set PATH=C:\Tools\NUnit3\bin;%PATH%
```

**Comment by mattiasnordqvist** [comment]
Excuse me for not being that familiar with the appveyor world. Where should I put/run the installation script?

**Comment by limanartem** [comment]
Settings > Environment > Installation Script > CMD

**Comment by luisrudge** [comment]
hey! This bit me today! Can we add nunit 3 support? Thanks

**Comment by jakejgordon** [comment]
+1

**Comment by FeodorFitsner** [comment]
Built-in support for NUnit 3.0 has been deployed. This is sample build: https://ci.appveyor.com/project/FeodorFitsner/nunit3-tests/build/1.0.12

**Comment by jakejgordon** [comment]
Hi @FeodorFitsner , can you explain this a little more for us AppVeyor newbies? If NUnit 3 is built-in now then shouldn't there just be an option for "Use NUnit 3 For Running Tests" or something on the testing tab? Or do we have to do something in the Environment => Installation Script still?

**Comment by FeodorFitsner** [comment]
Built-in support basically means NUnit 3 is supported by testing assemblies auto-discovery module ("Auto" mode on project test settings).



- Feodor

**Comment by twcclegg** [comment]
For my projects I just updated the nuget packages to point to NUnit 3.0.1 and it worked as desired.

**Comment by jakejgordon** [comment]
I'm getting the below when it runs the build. You can see that it says ```NUnit-Console version 2.6.4.14350```. So it seems like it isn't auto-detecting NUnit version 3.0.1 -- even though that is what I've got installed. Any ideas?

``` 
Time Elapsed 00:00:13.98
nunit-console ./Tests/UI.Tests/bin/Release/UI.Tests.dll
NUnit-Console version 2.6.4.14350
Copyright (C) 2002-2012 Charlie Poole.
Copyright (C) 2002-2004 James W. Newkirk, Michael C. Two, Alexei A. Vorontsov.
Copyright (C) 2000-2002 Philip Craig.
All Rights Reserved.
 
Runtime Environment - 
   OS Version: Microsoft Windows NT 6.2.9200.0
  CLR Version: 2.0.50727.8009 ( Net 3.5 )
 
ProcessModel: Default    DomainUsage: Single
Execution Runtime: net-3.5
Unhandled Exception:
NUnit.Core.UnsupportedFrameworkException: Skipped loading assembly UI.Tests because it references an unsupported version of the nunit.framework, 3.0.5813.39031
 
Server stack trace: 
   at NUnit.Core.Builders.TestAssemblyBuilder.GetCandidateFixtureTypes(Assembly assembly, String ns)
   at NUnit.Core.Builders.TestAssemblyBuilder.GetFixtures(Assembly assembly, String ns)
   at NUnit.Core.Builders.TestAssemblyBuilder.Build(String assemblyName, Boolean autoSuites)
   at NUnit.Core.Builders.TestAssemblyBuilder.Build(String assemblyName, String testName, Boolean autoSuites)
   at NUnit.Core.TestSuiteBuilder.BuildSingleAssembly(TestPackage package)
   at NUnit.Core.TestSuiteBuilder.Build(TestPackage package)
   at NUnit.Core.SimpleTestRunner.Load(TestPackage package)
   at NUnit.Core.ProxyTestRunner.Load(TestPackage package)
   at NUnit.Core.ProxyTestRunner.Load(TestPackage package)
   at NUnit.Core.RemoteTestRunner.Load(TestPackage package)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
 
Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at NUnit.Core.TestRunner.Load(TestPackage package)
   at NUnit.Util.TestDomain.Load(TestPackage package)
   at NUnit.Core.ProxyTestRunner.Load(TestPackage package)
   at NUnit.Util.RemoteTestAgent.AgentRunner.Load(TestPackage package)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
 
Exception rethrown at [1]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at NUnit.Core.TestRunner.Load(TestPackage package)
   at NUnit.Core.ProxyTestRunner.Load(TestPackage package)
   at NUnit.Util.ProcessRunner.Load(TestPackage package)
   at NUnit.ConsoleRunner.ConsoleUi.Execute(ConsoleOptions options)
   at NUnit.ConsoleRunner.Runner.Main(String[] args)
```

**Comment by FeodorFitsner** [comment]
Do you use default build worker image?

**Comment by twcclegg** [comment]
Perhaps it is because I'm using the VMs specifically for VS2015 but all I did was update to 3.0.1 in packages.config and .csprojs and everything just worked.

**Comment by FeodorFitsner** [comment]
NUnit 3.0 should work on all build workers.

**Comment by jakejgordon** [comment]
I think I'm using the default. My .yml is pretty basic I think: https://github.com/NemeStats/NemeStats/blob/master/appveyor.yml

@twcclegg How do you specifically use a VS2015 VM? When I started the project it was on VS2013 but I switched my solution to VS2015 a few months ago. AppVeyor only stopped running tests the other day when I updated my test projects to NUnit 3.0.1.

**Comment by FeodorFitsner** [comment]
In NUnit 3 console runner was renamed to "nunit3-console.exe". Also pay
attention to changed command line syntax.

-Feodor
On Wed, Dec 9, 2015 at 4:24 AM, Jake Gordon <notifications@github.com> wrote:
I think I'm using the default. My .yml is pretty basic I think: [https://github.com/NemeStats/NemeStats/blob/master/appveyor.yml] https://github.com/NemeStats/NemeStats/blob/master/appveyor.yml
[https://github.com/NemeStats/NemeStats/blob/master/appveyor.yml]

@twcclegg [https://github.com/twcclegg] How do you specifically use a VS2015 VM? When I started the project it was on
VS2013 but I switched my solution to VS2015 a few months ago. AppVeyor only
stopped running tests the other day when I updated my test projects to NUnit
3.0.1.

—
Reply to this email directly or view it on GitHub
[https://github.com/appveyor/ci/issues/498#issuecomment-163211029] .[https://github.com/notifications/beacon/AEztM6-vNEWPB2GTn6CL-As7-IC7uWNlks5pOBT6gaJpZM4GkGF7.gif]
