### ISSUE TITLE
FireFox 47

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#873]

**Comment by MikhailTymchukDX** [comment]
Hi,

I noticed today that my FireFox Selenium test simply can't run.
There are 2 error messages I see:

1.  https://ci.appveyor.com/project/dxrobot/ajaxcontroltoolkit/build/174
	```
	OpenQA.Selenium.WebDriverException : Failed to start up socket within 45000 milliseconds. Attempted to connect to the following addresses: 127.0.0.1:7055
	   at OpenQA.Selenium.Firefox.FirefoxDriverServer.ConnectToBrowser(TimeSpan timeToWait)
	   at OpenQA.Selenium.Firefox.FirefoxDriverServer.Start()
	   at OpenQA.Selenium.Firefox.FirefoxDriverCommandExecutor.Execute(Command commandToExecute)
	   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
	   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
	   at OpenQA.Selenium.Firefox.FirefoxDriver..ctor(FirefoxBinary binary, FirefoxProfile profile, ICapabilities capabilities, TimeSpan commandTimeout)
	   at OpenQA.Selenium.Firefox.FirefoxDriver..ctor(FirefoxBinary binary, FirefoxProfile profile, TimeSpan commandTimeout)
	   at AjaxControlToolkit.Tests.JasmineTests.FireFox() in c:\projects\ajaxcontroltoolkit\AjaxControlToolkit.Tests\JasmineTests.cs:line 38
	Run Settings
		WorkDirectory: C:\projects\ajaxcontroltoolkit
	```



2.  https://ci.appveyor.com/project/dxrobot/ajaxcontroltoolkit/build/175

	```
	OpenQA.Selenium.WebDriverException : A exception with a null response was thrown sending an HTTP request to the remote WebDriver server for URL http://localhost:7055/hub/session. The status of the exception was ReceiveFailure, and the message was: The underlying connection was closed: An unexpected error occurred on a receive.
	  ----> System.Net.WebException : The underlying connection was closed: An unexpected error occurred on a receive.
	  ----> System.IO.IOException : Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.
	  ----> System.Net.Sockets.SocketException : An existing connection was forcibly closed by the remote host
	   at OpenQA.Selenium.Remote.HttpCommandExecutor.CreateResponse(WebRequest request)
	   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
	   at OpenQA.Selenium.Firefox.FirefoxDriverCommandExecutor.Execute(Command commandToExecute)
	   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
	   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
	   at OpenQA.Selenium.Firefox.FirefoxDriver..ctor(FirefoxBinary binary, FirefoxProfile profile, ICapabilities capabilities, TimeSpan commandTimeout)
	   at OpenQA.Selenium.Firefox.FirefoxDriver..ctor(FirefoxBinary binary, FirefoxProfile profile, TimeSpan commandTimeout)
	   at AjaxControlToolkit.Tests.JasmineTests.FireFox() in c:\projects\ajaxcontroltoolkit\AjaxControlToolkit.Tests\JasmineTests.cs:line 38
	--WebException
	   at System.Net.HttpWebRequest.GetResponse()
	   at OpenQA.Selenium.Remote.HttpCommandExecutor.CreateResponse(WebRequest request)
	--IOException
	   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
	   at System.Net.PooledStream.Read(Byte[] buffer, Int32 offset, Int32 size)
	   at System.Net.Connection.SyncRead(HttpWebRequest request, Boolean userRetrievedStream, Boolean probeRead)
	--SocketException
	   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
	Run Settings
		WorkDirectory: C:\projects\ajaxcontroltoolkit
	```

Can you confirm this is because of the recent upgrade?

**Comment by MikhailTymchukDX** [comment]
Just checked locally: FireFox 47 crashes on test startup. Reverting to earlier version for now.

**Comment by FeodorFitsner** [comment]
You're right - there is an issue with FF 47 and Selenium: https://github.com/SeleniumHQ/selenium/issues/2110

We'll rollback to FF 46 and re-deploy build worker images.

**Comment by FeodorFitsner** [comment]
I've updated FireFox to 47.0.1 and published an article on how to use Selenium with FF 47: http://www.appveyor.com/docs/how-to/selenium-testing
