### ISSUE TITLE
node-gyp rebuild fails on newest configurations

### ISSUE THREAD

**Issue by reidmweber** [appveyor/ci#904]
Our builds for Electron Desktop were building successfully until the June 27 update. I tried using Previous Visual Studio 2015 in my appveyor.yml file but I believe that just takes me back to the June 27th release from the June 28th current release. I'm pretty sure this is an issue with the appveyor environment because I went back and tried to rebuild a build that had succeeded before June 27 and now it fails. 
Here is the error :
```
Warning: Missing input files:
C:\Users\appveyor\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.cc
```
Here is the error with more context:
```
> nslog@3.0.0 install C:\projects\sufferfestwindows\node_modules\nslog
> node-gyp rebuild
C:\projects\sufferfestwindows\node_modules\nslog>if not defined npm_config_node_gyp (node "C:\Users\appveyor\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild ) 
Warning: Missing input files:
C:\Users\appveyor\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.cc
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  main.cc
  nslog_win.cc
  win_delay_load_hook.cc
c1xx : fatal error C1083: Cannot open source file: 'C:\Users\appveyor\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.cc': No such file or directory [C:\projects\sufferfestwindows\node_modules\nslog\build\nslog.vcxproj]
gyp ERR! build error 
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\appveyor\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\appveyor\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\projects\sufferfestwindows\node_modules\nslog
gyp ERR! node -v v6.2.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
```

**Comment by FeodorFitsner** [comment]
This might be Update 3. However, `Previous Visual Studio 2015` is currently pointing to [June 25th update](http://www.appveyor.com/updates/2016/06/25) which is Update 2.

**Comment by FeodorFitsner** [comment]
A new image `Visual Studio 2015 Update 2` has been added to your account. It will be there until you have a fix for that issue with VS 2015 Update 3. No new software/updates will be installed to that image.
