### ISSUE TITLE
pyyaml wheel doesn't build for Python 3.4 Windows 64-bit

### ISSUE THREAD

**Issue by goelakash** [appveyor/ci#968]
Here"s the test log:
https://ci.appveyor.com/project/ethanwhite/retriever/build/1.0.333/job/lni97e6ts9ytgms2
```
[00:00:13] Collecting pyyaml (from -r requirements.txt (line 8))
[00:00:13] 
[00:00:13]   Downloading PyYAML-3.11.zip (371kB)
[00:00:13] 
[00:00:14] Collecting pockets>=0.3 (from sphinxcontrib-napoleon->-r requirements.txt (line 7))
[00:00:14] 
[00:00:14]   Downloading pockets-0.3-py2.py3-none-any.whl (60kB)
[00:00:14] 
[00:00:14] Collecting six>=1.5.2 (from sphinxcontrib-napoleon->-r requirements.txt (line 7))
[00:00:14] 
[00:00:14]   Downloading six-1.10.0-py2.py3-none-any.whl
[00:00:14] 
[00:00:14] Building wheels for collected packages: future, numpydoc, pyyaml
[00:00:14] 
[00:00:14]   Running setup.py bdist_wheel for future: started
[00:00:14] 
[00:00:15]   Running setup.py bdist_wheel for future: finished with status 'done'
[00:00:15] 
[00:00:15]   Stored in directory: C:\Users\appveyor\AppData\Local\pip\Cache\wheels\11\c5\d2\ad287de27d0f0d646f119dcffb921f4e63df128f28ab0a1bda
[00:00:15] 
[00:00:15]   Running setup.py bdist_wheel for numpydoc: started
[00:00:15] 
[00:00:16]   Running setup.py bdist_wheel for numpydoc: finished with status 'done'
[00:00:16] 
[00:00:16]   Stored in directory: C:\Users\appveyor\AppData\Local\pip\Cache\wheels\9d\ca\8c\9be286b195791bbbfebfd407899de13eb12725a2c2c9fdb36f
[00:00:16] 
[00:00:16]   Running setup.py bdist_wheel for pyyaml: started
[00:00:16] 
[00:00:16]   Running setup.py bdist_wheel for pyyaml: finished with status 'error'
[00:00:16] 
[00:00:16]   Complete output from command C:\Python34-x64\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-build-d9cm0145\\pyyaml\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d C:\Users\appveyor\AppData\Local\Temp\1\tmpg6lica48pip-wheel- --python-tag cp34:
[00:00:16] 
[00:00:16]   running bdist_wheel
[00:00:16]   running build
[00:00:16]   running build_py
[00:00:16]   creating build
[00:00:16]   creating build\lib.win-amd64-3.4
[00:00:16]   creating build\lib.win-amd64-3.4\yaml
[00:00:16]   copying lib3\yaml\composer.py -> build\lib.win-amd64-3.4\yaml
[00:00:16]   copying lib3\yaml\constructor.py -> build\lib.win-amd64-3.4\yaml
[00:00:16]   copying lib3\yaml\cyaml.py -> build\lib.win-amd64-3.4\yaml
[00:00:16]   copying lib3\yaml\dumper.py -> build\lib.win-amd64-3.4\yaml
[00:00:16]   copying lib3\yaml\emitter.py -> build\lib.win-amd64-3.4\yaml
[00:00:16]   copying lib3\yaml\error.py -> build\lib.win-amd64-3.4\yaml
[00:00:16]   copying lib3\yaml\events.py -> build\lib.win-amd64-3.4\yaml
[00:00:16]   copying lib3\yaml\loader.py -> build\lib.win-amd64-3.4\yaml
[00:00:16]   copying lib3\yaml\nodes.py -> build\lib.win-amd64-3.4\yaml
[00:00:16]   copying lib3\yaml\parser.py -> build\lib.win-amd64-3.4\yaml
[00:00:16]   copying lib3\yaml\reader.py -> build\lib.win-amd64-3.4\yaml
[00:00:16]   copying lib3\yaml\representer.py -> build\lib.win-amd64-3.4\yaml
[00:00:16]   copying lib3\yaml\resolver.py -> build\lib.win-amd64-3.4\yaml
[00:00:16]   copying lib3\yaml\scanner.py -> buil
[00:00:16] d\lib.win-amd64-3.4\yaml
[00:00:16]   copying lib3\yaml\serializer.py -> build\lib.win-amd64-3.4\yaml
[00:00:16]   copying lib3\yaml\tokens.py -> build\lib.win-amd64-3.4\yaml
[00:00:16]   copying lib3\yaml\__init__.py -> build\lib.win-amd64-3.4\yaml
[00:00:16]   running build_ext
[00:00:16]   creating build\temp.win-amd64-3.4
[00:00:16]   creating build\temp.win-amd64-3.4\Release
[00:00:16]   checking if libyaml is compilable
[00:00:16]   Traceback (most recent call last):
[00:00:16]     File "<string>", line 1, in <module>
[00:00:16]     File "C:\Users\appveyor\AppData\Local\Temp\1\pip-build-d9cm0145\pyyaml\setup.py", line 342, in <module>
[00:00:16]       'test': test,
[00:00:16]     File "C:\Python34-x64\lib\distutils\core.py", line 148, in setup
[00:00:16]       dist.run_commands()
[00:00:16]     File "C:\Python34-x64\lib\distutils\dist.py", line 955, in run_commands
[00:00:16]       self.run_command(cmd)
[00:00:16]     File "C:\Python34-x64\lib\distutils\dist.py", line 974, in run_command
[00:00:16]       cmd_obj.run()
[00:00:16]     File "C:\Python34-x64\lib\site-packages\wheel\bdist_wheel.py", line 179, in run
[00:00:16]       self.run_command('build')
[00:00:16]     File "C:\Python34-x64\lib\distu
[00:00:16] tils\cmd.py", line 313, in run_command
[00:00:16]       self.distribution.run_command(command)
[00:00:16]     File "C:\Python34-x64\lib\distutils\dist.py", line 974, in run_command
[00:00:16]       cmd_obj.run()
[00:00:16]     File "C:\Python34-x64\lib\distutils\command\build.py", line 126, in run
[00:00:16]       self.run_command(cmd_name)
[00:00:16]     File "C:\Python34-x64\lib\distutils\cmd.py", line 313, in run_command
[00:00:16]       self.distribution.run_command(command)
[00:00:16]     File "C:\Python34-x64\lib\distutils\dist.py", line 974, in run_command
[00:00:16]       cmd_obj.run()
[00:00:16]     File "C:\Users\appveyor\AppData\Local\Temp\1\pip-build-d9cm0145\pyyaml\setup.py", line 169, in run
[00:00:16]       _build_ext.run(self)
[00:00:16]     File "C:\Python34-x64\lib\distutils\command\build_ext.py", line 339, in run
[00:00:16]       self.build_extensions()
[00:00:16]     File "C:\Users\appveyor\AppData\Local\Temp\1\pip-build-d9cm0145\pyyaml\setup.py", line 211, in build_extensions
[00:00:16]       with_ext = self.check_extension_availability(ext)
[00:00:16]     File "C:\Users\appveyor\AppData\Local\Temp\1\pip-build-d9cm0145\pyyaml\setup.py", line 237
[00:00:16] , in check_extension_availability
[00:00:16]       depends=ext.depends)
[00:00:16]     File "C:\Python34-x64\lib\distutils\msvc9compiler.py", line 460, in compile
[00:00:16]       self.initialize()
[00:00:16]     File "C:\Python34-x64\lib\distutils\msvc9compiler.py", line 371, in initialize
[00:00:16]       vc_env = query_vcvarsall(VERSION, plat_spec)
[00:00:16]     File "C:\Python34-x64\lib\site-packages\setuptools\msvc9_support.py", line 52, in query_vcvarsall
[00:00:16]       return unpatched['query_vcvarsall'](version, *args, **kwargs)
[00:00:16]     File "C:\Python34-x64\lib\distutils\msvc9compiler.py", line 287, in query_vcvarsall
[00:00:16]       raise ValueError(str(list(result.keys())))
[00:00:16]   ValueError: ['path']
[00:00:16]   
[00:00:16]   ----------------------------------------
[00:00:16]   Failed building wheel for pyyaml
[00:00:16] 
[00:00:16]   Running setup.py clean for pyyaml
[00:00:16] 
[00:00:16] Successfully built future numpydoc
[00:00:16] 
[00:00:16] Failed to build pyyaml
```

**Comment by XhmikosR** [comment]
@FeodorFitsner: Seems like it needs VS2008 to build?

**Comment by FeodorFitsner** [comment]
There is Visual C++ 2008 Express installed: http://www.appveyor.com/docs/installed-software#visual-studio-2008 - shouldn't be enough?

**Comment by XhmikosR** [comment]
Should be yes. But for x64 the user would need the SDK IIRC. Hence the failure, I suspect.

**Comment by cclauss** [comment]
Can this issue be closed?
